import Head from 'next/head'
import Image from 'next/image'
import style from  '../styles/Home.module.scss'

//
import { About , Footer , Header, Skills, Testimonial, Works  } from '@/containers'
import { Navbar } from '@/components'

import { urlFor, client } from '@/client'

import { images } from '@/constants'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';

interface about{
  title: string,
  description: string,
  imgUrl?: any
}

interface props{
  navBarDetails: string[],
  abouts: about[],
  works: any,
  skills: any,
  testimonials : any,
}

export default function Home({navBarDetails,abouts, works,skills,testimonials} : props) {
  console.log(process.env.NEXT_APP__SANITY_PROJECT_ID,'is the id')
  const TITLE = `Adwaith's portfolio`
  return (
    <div className={style.app}>
      <Head>
        <title>{TITLE}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar navBarDetails={navBarDetails} />
      <Header />
      <About abouts={abouts}  />
      <Works works = {works} />
      <Skills skills = {skills} />
      <Testimonial testimonials={testimonials} />
      <Footer />
      <ToastContainer />
    </div>
  )
}

Home.getInitialProps = async(ctx : any) => {
  const navBarDetails: string[] = ['home', 'about' , 'skills', 'works' , 'testimonials', 'contact' ]
  // I have to change this any's to proper type later
  let works: any
  let skills: any
  let testimonials : any
  let abouts: about[] = [
    {
      title: 'Front-end',
      description: 'React.js, Next.js, MUI, Scss, Bootstrap',
      imgUrl: images.about01
    },
    {
      title: 'Back-end',
      description: 'Node.js, Nest.js, Docker, Microservices, Mongodb',
      imgUrl: images.about02
    },
    {
      title: 'Programming-languages',
      description: 'Javascript, Typescript',
      imgUrl: images.about03
    },
    {
      title: 'Soft Skills',
      description: 'Communication, Leadership, Fast learning, Teamwork',
      imgUrl: images.about04
    }
  ]

  const queryForAbout = '*[_type == "abouts"]'

 await client.fetch(queryForAbout).then((data) => {
    abouts = data
    console.log(data,'is the data')
  })

const queryForWork = '*[_type == "works"]'
  await client.fetch(queryForWork).then((data) => {
    works = data
  })

  const queryForSkills = '*[_type == "skills"]'
  await client.fetch(queryForSkills).then((data) => {
    skills = data
  })

  const queryForTestimonials = '*[_type == "testimonials"]'
    await client.fetch(queryForTestimonials).then((data) => {
      testimonials = data
    })

  return{navBarDetails,abouts,works,skills,testimonials}
}
